### PR TITLE
v: Update to V 0.4.5 ed7f1ff

### PR DESCRIPTION
**Pull request by elliotchance**
This aggregates the awesome work by @ttytm in #192, #193, #194 and #195.

### CODE REVIEW

**Review by spytheman — APPROVED** [review]
Excellent.

**Comment by ttytm** [comment]
Would be even more excellent if at least a tiny attribution would be left

**Comment by elliotchance** [comment]
@ttytm - I didn't want to land multiple PRs that were broken individually broken builds. I was going to add a description crediting the other PRs before this landed, but since this all your work I'm happy for you to resubmit the patch and I'll close this one so it can be actually signed under you.

**Comment by ttytm** [comment]
> @ttytm - I didn't want to land multiple PRs that were broken individually broken builds. I was going to add a description crediting the other PRs before this landed, but since this all your work I'm happy for you to resubmit the patch and I'll close this one so it can be actually signed under you.

Thank you. Mentioning it as a principle is just what was important to me. Gaining a personal attribution from it, less, I don't have too much control over that.

**Pull request merged**
