### PR TITLE
sequences: Fixing concurrent "NEXT VALUE FOR"

### PR DESCRIPTION
**Pull request by elliotchance**
This fixes a bug where concurrent transactions using "NEXT VALUE FOR" would make the sequence invisible to the other concurrent transaction.

The properties of a sequence (such as the `INCREMENT BY`, etc) are held in the same record as the next value. Since the next value of a sequence needs to be atomic (and separate from the transaction isolation) a `ROLLBACK` on a transaction that contains an `ALTER SEQUENCE` will not undo any changes.

Ideally, the properties of a `SEQUENCE` can be stored in a separate location on disk. However, for now it's a documented limitation.

### CODE REVIEW

**Comment by dumblob** [comment]
I wonder if the documented limitation of non-functional rollback is planned to be lifted at some point in the future or if it is rather meant to be accepted as part of the "minimalism" of this SQL library.

Thanks!

**Comment by elliotchance** [comment]
Reading it back now, i think I made it sound more complicated to fix than it actually should be. There is an [object type that represents the sequence](https://vsql.readthedocs.io/en/latest/file-format.html#sequence-object) which also contains the next value. The fix would be to separate the next value stored on the sequence definition into a new object type. Then the sequence definition could be tried to transaction.

**Comment by dumblob** [comment]
I see, thanks for explanation.

So, is this limitation planned to be removed in the "near" future or rarther not?

**Comment by dumblob** [comment]
No need to hurry - I just wanted to have the vision clarified :wink:.

**Comment by elliotchance** [comment]
@dumblob fixed: https://github.com/elliotchance/vsql/releases/tag/v0.27.7

**Comment by dumblob** [comment]
Thanks a lot @elliotchance !

I am really pleased to see what vsql already achieved and how it evolves.

**Pull request merged**
